repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
  - repo: https://github.com/pappasam/toml-sort
    rev: v0.23.1
    hooks:
      - id: toml-sort-fix
        args: ["--in-place", "pyproject.toml"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/PyCQA/pylint
    rev: v3.2.4
    hooks:
      - id: pylint
        fail_fast: false
        args:
          - --disable=E0401 # 忽略 "Unable to import" 錯誤
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["--severity-level", "all", "--exclude", "tests/"]
        fail_fast: false
  - repo: https://github.com/PyCQA/docformatter
    rev: eb1df347edd128b30cd3368dddc3aa65edcfac38 # https://github.com/PyCQA/docformatter/issues/293
    hooks:
      - id: docformatter
        additional_dependencies: [tomli]
  - repo: https://github.com/google/yamlfmt
    rev: v0.10.0
    hooks:
      - id: yamlfmt
