name: To Be Review

on:
  schedule: [{cron: "0 0 */14 * *"}]
  
jobs:
  sync:
    name: Open Issue and Update State
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Open Issue and Update State
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python create_issue_to_review.py --github-username hsiangjenli
      
      - name: Commit and Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git fetch origin
          git checkout main
          
          # 如果有未提交的更改，暫存起來
          git diff --quiet || git stash

          # 拉取遠端更改並使用 rebase 確保提交記錄乾淨
          git pull origin main --rebase || git rebase --abort

          # 恢復暫存的更改（如果有）
          git stash pop || echo "No stashed changes to apply"

          # 設定使用者資訊
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # 提交變更（如果有新的改動）
          git add .
          git commit -m "bot: open issue and update state" || echo "No changes to commit"

          # 推送到遠端
          git push origin main
